### ISSUE TITLE
We're finally running testing

### ISSUE THREAD

**Issue by matt-ketk** [UWMRO/ScienceCamera#54]
As of b1b2bfd, running `test_server.py` outputs the following:

```
[DEBUG/evora_server.py:477] 2021-09-02 14:36:59 (MainProcess/MainThread)
> Aborted: None
.EEEEE
[DEBUG/evora_server.py:372] 2021-09-02 14:36:59 (MainProcess/MainThread)
> [20036, 32]

[DEBUG/evora_server.py:374] 2021-09-02 14:36:59 (MainProcess/MainThread)
> 55

[DEBUG/evora_server.py:379] 2021-09-02 14:36:59 (MainProcess/MainThread)
> <MagicMock name='SetTemperature()' id='140111582459408'>
.
[DEBUG/evora_server.py:372] 2021-09-02 14:36:59 (MainProcess/MainThread)
> [1, 32]

[DEBUG/evora_server.py:374] 2021-09-02 14:36:59 (MainProcess/MainThread)
> 32

[DEBUG/evora_server.py:379] 2021-09-02 14:36:59 (MainProcess/MainThread)
> None
.
[DEBUG/evora_server.py:372] 2021-09-02 14:36:59 (MainProcess/MainThread)
> [20034, 32]

[DEBUG/evora_server.py:374] 2021-09-02 14:36:59 (MainProcess/MainThread)
> 72

[DEBUG/evora_server.py:379] 2021-09-02 14:36:59 (MainProcess/MainThread)
> <MagicMock name='SetTemperature()' id='140111566895248'>
.
[DEBUG/evora_server.py:408] 2021-09-02 14:36:59 (MainProcess/MainThread)
> [1, 1]

[INFO/evora_server.py:439] 2021-09-02 14:36:59 (MainProcess/MainThread)
> closing down camera connection
EE
[DEBUG/evora_server.py:408] 2021-09-02 14:36:59 (MainProcess/MainThread)
> [1, 1]
EEEEEE
======================================================================
ERROR: test_parse_expose (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 99, in test_parse_expose
    self.assertTrue(self.parser.parse('expose').contains("expose "))
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 232, in parse
    imType = input[1]
IndexError: list index out of range

======================================================================
ERROR: test_parse_getTEC (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 59, in test_parse_getTEC
    self.assertTrue(self.parser.parse('getTEC').contains(','))
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 173, in parse
    return self.e.getTEC()
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 362, in getTEC
    str(coolerStatusNames[result[0] - andor.DRV_TEMPERATURE_OFF]) + " " + str(result[1]))
IndexError: tuple index out of range

======================================================================
ERROR: test_parse_horzStats (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 93, in test_parse_horzStats
    self.assertTrue(self.parser.parse('horzStats') == '') # unfinished
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 211, in parse
    return self.e.horizontalSpeedStats(int(input[1]), int(input[2]),
IndexError: list index out of range

======================================================================
ERROR: test_parse_real (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 102, in test_parse_real
    self.assertTrue(self.parser.parse('real') == 'real 1')
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 260, in parse
    imType = input[1]
IndexError: list index out of range

======================================================================
ERROR: test_parse_series (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 105, in test_parse_series
    self.assertTrue(self.parser.parse('series').contains('series 1,'))
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 277, in parse
    imType = input[1]
IndexError: list index out of range

======================================================================
ERROR: test_parse_shutdown (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 26, in test_parse_shutdown
    self.assertTrue(self.parser.parse('shutdown') == 'shutdown 1')
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 185, in parse
    return self.e.shutdown()
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 440, in shutdown
    andor.ShutDown()
AttributeError: 'module' object has no attribute 'ShutDown'

======================================================================
ERROR: test_parse_status (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 87, in test_parse_status
    self.assertTrue(self.parser.parse('status').isnumeric())
AttributeError: 'str' object has no attribute 'isnumeric'

======================================================================
ERROR: test_parse_temp (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 13, in test_parse_temp
    self.assertTrue(self.parser.parse('temp').isnumeric())
AttributeError: 'str' object has no attribute 'isnumeric'

======================================================================
ERROR: test_parse_temprange (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 16, in test_parse_temprange
    self.assertTrue(self.parser.parse('tempRange').contains('-'))
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 158, in parse
    return self.e.getTempRange()
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 417, in getTempRange
    stats = andor.GetTemperatureRange()
TypeError: GetTemperatureRange() takes exactly 2 arguments (0 given)

======================================================================
ERROR: test_parse_temprange_runs_andor_function (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mattketk/.local/lib/python2.7/site-packages/mock/mock.py", line 1330, in patched
    return func(*args, **keywargs)
  File "../tests/test_server.py", line 23, in test_parse_temprange_runs_andor_function
    self.assertTrue(res.contains('5,10,15'))
AttributeError: 'str' object has no attribute 'contains'

======================================================================
ERROR: test_parse_timings (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 29, in test_parse_timings
    self.assertTrue(self.parser.parse('timings') == 'timings')
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 199, in parse
    return self.e.getTimings()
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 449, in getTimings
    expTime, accTime, kTime = andor.GetAcquisitionTimings()
TypeError: GetAcquisitionTimings() takes exactly 3 arguments (0 given)

======================================================================
ERROR: test_parse_vertStats (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 90, in test_parse_vertStats
    self.assertTrue(self.parser.parse('vertStats') == '') # unfinished
  File "/home/mattketk/Development/ScienceCamera/evora/server/server.py", line 205, in parse
    return self.e.verticalSpeedStats(int(input[1]))
IndexError: list index out of range

======================================================================
ERROR: test_parse_warmup (__main__.TestEvoraParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_server.py", line 65, in test_parse_warmup
    self.assertTrue(self.parser.parse('warmup').contains('warmup '))
AttributeError: 'str' object has no attribute 'contains'

----------------------------------------------------------------------
Ran 17 tests in 0.007s

FAILED (errors=13)
```

**Comment by matt-ketk** [comment]
## Checklist

- [ ]  ERROR: test_parse_expose
- [ ] ERROR: test_parse_getTEC
- [ ] ERROR: test_parse_horzStats
- [ ] ERROR: test_parse_real
- [ ] ERROR: test_parse_series
- [ ] ERROR: test_parse_shutdown
- [ ] ERROR: test_parse_status
- [ ] ERROR: test_parse_temp
- [ ] ERROR: test_parse_temprange
- [ ] ERROR: test_parse_temprange_runs_andor_function
- [ ] ERROR: test_parse_timings
- [ ] ERROR: test_parse_vertStats
- [ ] ERROR: test_parse_warmup
